# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest

    working_directory: ~/repo

    steps:
      - checkout

      - run: yarn install

      # run tests!
      # - run: yarn test
      - run: 
          name: Build docs
          command: yarn build
      - store_artifacts:
          path: dist/ng-hnefatafl
      #- persist_to_workspace:
      #    root: dist/ng-hnefatafl
      #    paths: html

  docs-deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - attach_workspace:
          at: dist/ng-hnefatafl
      - run:
          name: Install and configure dependencies
          command: |
            yarn add gh-pages
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "dd:6c:cf:fb:2b:ba:29:68:c0:eb:1e:a6:24:06:10:66"
      - run:
          name: Deploy docs to gh-pages branch
          command: yarn deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - docs-deploy:
          requires:
            - build
